# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    exclude:
    - master
  paths:
    include:
    - ./*.js

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    echo $(System.PullRequest.SourceBranch) > $(Build.ArtifactStagingDirectory)/pr_source_branch
  displayName: 'store branch name to file'

- script: |
    npm install
    npm run lint
  displayName: 'npm install and lint'

- script: |
    npm test
    CODECOV_TOKEN=$(CODECOV_TOKEN) npm run report-coverage
  displayName: 'test and upload coverage'

- script: |
    SHORT_COMMIT=`echo $(Build.SourceVersion)| cut -c1-7`
    echo $SHORT_COMMIT > $(System.DefaultWorkingDirectory)/deploy.sha
  displayName: 'store commit SHA in file'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
